openapi: 3.0.3
info:
  title: Guitar Plugins Catalog API
  description: Учебный проект API-документации каталога гитарных плагинов для портфолио.
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Проверка связи с сервером
      responses:
        '200':
          description: Сервер работает отлично!
